name: terraform-ci
on:
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  security-scan:
    uses: ./.github/workflows/security-scan.yaml

  plan:
    needs: [lint, validate, security-scan]
    uses: ./.github/workflows/terraform-plan.yaml
    secrets: inherit

  document:
    needs: [plan]
    uses: ./.github/workflows/document.yaml

#   version:
#     needs: [document]
#     uses: ./.github/workflows/version.yaml
