name: Terraform Apply
on:
  workflow_call:
  workflow_dispatch:
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: examples

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Switch to the examples directory
        run: cd examples

      - name: Run Terraform Apply
        run: terraform apply "this.tfplan"
