name: Terraform Plan
on:
  workflow_call:
  push:
    branches:
      - main
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Switch to the examples directory
        run: cd examples

      - name: Run Terraform Init and Plan
        run: |
          terraform init -backend=false
          terraform plan -out=this.tfplan
        env:
          TF_VAR_github_run_id: ${{ github.run_id }}
          TF_VAR_github_run_number: ${{ github.run_number }}
          TF_VAR_github_sha: ${{ github.sha }}
          TF_VAR_github_ref_name: ${{ github.head_ref }}
          TF_VAR_github_actor: ${{ github.actor }}
          TF_VAR_github_repository: ${{ github.repository }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: examples/this.tfplan
