name: terraform-ci
on:
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  security-scan:
    uses: ./.github/workflows/security-scan.yaml

  terraform:
    needs: [lint, validate, security-scan]
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit

  document:
    needs: [terraform]
    uses: ./.github/workflows/document.yaml
