name: terraform-ci
on:
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate:
    uses: ./.github/workflows/terraform-validate.yaml

  lint:
    uses: ./.github/workflows/tflint-run.yaml

  security-scan:
    uses: ./.github/workflows/tfsec-run.yaml

  terraform-plan:
    needs: [lint, validate, security-scan]
    uses: ./.github/workflows/terraform-plan.yaml
    secrets: inherit

  terraform-apply:
    needs: [terraform-plan]
    uses: ./.github/workflows/terraform-apply.yaml
    secrets: inherit

  terraform-destroy:
    needs: [terraform-apply]
    uses: ./.github/workflows/terraform-destroy.yaml
    secrets: inherit

  document:
    needs: [terraform-destroy]
    uses: ./.github/workflows/terraform-docs-run.yaml
