name: Terraform Destroy
on:
  workflow_call:
  workflow_dispatch:
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Switch to the examples directory
        run: cd examples

      - name: Run Terraform Destroy
        run: terraform destroy -auto-approve
